### ISSUE TITLE
Filtering products by numerical attributes with units do not work

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/saleor-dashboard#2673]
### Description of the issue

I want to filter the products list by attributes that have a number + unit (`500ml`).

### Steps to reproduce the problem

1. Go to the dashboard product list page
2. Try to filter by an attribute that has a number and a unit

### Expected Result

Filter is applied

### Actual Result

Error from core

### Screenshots
<img width="803" alt="image (2)" src="https://user-images.githubusercontent.com/9116238/203811540-41ec6947-8af4-43fd-8a4f-90f6d4af0903.png">
<img width="1728" alt="image (1)" src="https://user-images.githubusercontent.com/9116238/203811546-f8f2a793-27c9-4dc1-8d6f-b5e5db37a4de.png">

### HTTP request and response from the inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:

`v3.8.6`

Core version:

`v3.8.9`

Operating system:

- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by orzechdev** [comment]
The mentioned attribute (`500ml`) doesn't have number and unit, it's dropdown type attribute with multiple values. The problem is that we parse attribute values from URL params, so if user defines number as one of possible value e.g. mentioned `500ml`, it is parsed and treated as number and passed into GraphQL query variables as number range, so error occurs. To fix it properly we need to take into account attribute input type and only based on this parse an attribute value and define an input format of it in GraphQL query variables.
