### ISSUE TITLE
dashboard URL settings

### ISSUE THREAD

**Issue by patricxu** [saleor/saleor-dashboard#3600]
I have a problem with my dashboard setting. the API_URI is correct and I can get the response from graphql. However, there are some other URL setting errors when loads the items in the porduct list. The reqest URL of the item images are pointed to "http://localhost:8000/thumbnail/UHJvZHVjdE1lZGlhOjM2/256/"
which should be "http://a_real_ip:8000/thumbnail/UHJvZHVjdE1lZGlhOjM2/256/".
I have set the real ip as a env STATIC_IP when docker run, but it fails.

![image](https://user-images.githubusercontent.com/9252137/236493700-26448b82-9525-40da-968e-9bfcddb07b65.png)

the docker command is 

sudo docker run --publish 8080:80 --env "API_URL=http://a_real_ip:8000/graphql/" --env "STATIC_URL=http://a_real_ip:8000/" saleor-dashboard

I don't know why the STATIC_URL variable does not take effect. 

THANKS!

**Comment by maximilianhomburg** [comment]
Hi,
I had the same problem a few days ago. The problem was not with Saleor dashboard, but with the Saleor core API. I performed this `` mutation ShopDomainUpdate{
  shopDomainUpdate(input: {domain: "yourdomain.com"}){
    shop{
      domain{
        host
      }
    }
  }
}``   and then it worked. 

You can do this via the GraphQL Playground but remember to authorise first with this mutation`
mutation myMutation {
  tokenCreate(email: "user@example.com", password: "password") {
    token
    refreshToken
    errors {
      field
      message
    }
  }
}`

Then you can add the respective token into the Header with `
{
  "Authorization": "Bearer <your-token>"
}
`

Hope this helps!

**Comment by patricxu** [comment]
Thanks! I will try that. it maight be some hidden env not mentioned in the docs.

**Comment by acidlake** [comment]
Thanks a lot, this worked as expected!

**Comment by w-t-w** [comment]
> Hi, I had the same problem a few days ago. The problem was not with Saleor dashboard, but with the Saleor core API. I performed this ` mutation ShopDomainUpdate{ shopDomainUpdate(input: {domain: "yourdomain.com"}){ shop{ domain{ host } } } }` and then it worked.
> 
> You can do this via the GraphQL Playground but remember to authorise first with this mutation` mutation myMutation { tokenCreate(email: "user@example.com", password: "password") { token refreshToken errors { field message } } }`
> 
> Then you can add the respective token into the Header with `{ "Authorization": "Bearer <your-token>" }`
> 
> Hope this helps!

How to add { "Authorization": "Bearer <your-token>" }, any config?

**Comment by maximilianhomburg** [comment]
Hej, I don‘t exactly get your question, sorry. 

But if you are asking how you can add the Bearer-Token to your request:
In the GraphQL Playground you have the option to add a Header to your request. That’s where you can put your token.
