### ISSUE TITLE
[Bug]: Unable to save attribute value

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#3769]
### Description of the issue

A user cannot save the attribute.

### Steps to reproduce the problem

1. Go to the attributes
2. Edit some attribute value
3. Click save
4. An error of "INVALID on field value" pops up

### What did you expect to happen?

Value should be updated normally.

### Additional information

Issue probably is related to attributes that are type of "PRODUCT_TYPE

### Environment

Dashboard version: 3.14
Core version: 3.14

**Comment by poulch** [comment]
I determined after long research that the bug is caused due to wrong migration on the client database that cause that attributeValue for dropdown attribute type to have a specific value but shouldn't have.
I got confirmation from CORE that a value for attributeValue is required only when the attribute has an input type equal swatch.
