### ISSUE TITLE
[Feature]: Remove order related section on home page

### ISSUE THREAD

**Issue by poulch** [saleor/saleor-dashboard#4439]
### Description of the feature

I'd like to remove those sections from the home page due to the high impact on API usage.
<img width="1727" alt="Screenshot 2023-11-14 at 13 34 29" src="https://github.com/saleor/saleor-dashboard/assets/16362049/dd9512fa-6053-41a2-ac51-03722a0c1ef9">

### Acceptable criteria

- [ ] As a User I should not see order stats on home page

**Comment by pitkes22** [comment]
Sad to see those removed. Our staff was watching those numbers daily. Is there any plan for replacing them in any way?

**Comment by andrzejewsky** [comment]
@pitkes22 yes, we don't want to resign from metrics at all. We will go towards something more reliable in the future. For now these real time metrics were removed due to performance issues. In the current form they were are tough for the database (using counts), that's why we had to get rid of for now.
